version: '2'
services:
    montibeller_test-app:
        image: montibeller_test
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://montibeller_test-mysql:3306/montibeller_test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    montibeller_test-mysql:
        extends:
            file: mysql.yml
            service: montibeller_test-mysql
